# Generated by Django 4.1 on 2022-08-10 12:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
